---
title: "Sauces"
author: "Derek Sollberger"
date: "2024-12-14"
categories: [pantry]
---

* caution: I am not a food safety expert nor have I assured that the following will abide by food safety regulations

## Chili Crisp

Here I wanted to make myself a simplified version of [Brian Lagerstrom's recipe](https://www.youtube.com/watch?v=-wgZ7s3YxWI).  For each desired Mason jar (4 cups) of sauce ...

* 700g peanut oil
* 2 cinnamon sticks
* 4 pods star anise
* 2g Szechuan peppercorn
* 70g gochugaru (course flakes)
* 70g garlic (chopped)

Heat oil to 300 F.  Toss in above ingredients and let simmer for a couple of minutes, then strain.

* 1/2 cup peanuts (chopped, unsalted)
* 1/4 cup honey

## Nuoc Mam

* 1 part sugar (e.g. 0.5 cup)
* 1 part fish sauce (e.g. 0.5 cup)
* 1 tbsp minced garlic
* 1 tbsp chili sauce
* 3 parts boiling water (e.g. 1.5 cups)

mix into a Mason jar


## Tartar Sauce

* 1 cup mayonnaise

    * 1 whole egg
    * 1 additional egg yolk,
    * 1 cup "neutral" vegetable oil
    
* 1 dill pickle, chopped
* 1 tbsp pickle brine
* 1 tbsp pickled jalapenos
* 1 tsp dried dill
* 1 tsp Worcestershire sauce
* 1 tsp Dijon mustard
* 1 tbsp lemon juice (maybe wait until serving)

















